### ISSUE TITLE
header muss richtig positioniert werden

### ISSUE THREAD

**Issue by cookiengineer** [mm-automation/rapporter#1]
Das `<header>` element muss richtig positioniert werden.

Momentan gibt es keine CSS Regeln fuer den `header`. Diese muessen hinzugefuegt werden.

Zu tun ist folgendes in der `design/index.css` (am Ende der Datei):

- Erstelle eine CSS Regel fuer den Selektor `header` hinzu
- Der header muss mit `fixed` positioniert werden
- Der header braucht korrekte Angaben fuer `top`, `right`, `bottom`, `left`. Diese sollen (von den Werten her) gegenteilig zu `footer` sein.

**Comment by cookiengineer** [comment]
Lesematerial um obige Anweisungen zu verstehen:

- https://wiki.selfhtml.org/wiki/CSS/Eigenschaften/Positionierung/position

**Comment by chocojunky** [comment]
möhh
